name: 'Test'

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - apps/**

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm test
      - run: pnpm build
      - run: pnpm --recursive publish --no-git-checks --dry-run
