name: 'zugriff: Deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/**
      - docs/**
      - examples/**

jobs:
  deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - './apps/docs/**'
              - './.github/workflows/zugriff.yml'
            vanilla_ts:
              - './examples/vanilla-ts/**'
              - './packages/vite-plugin-retouche/**'
              - './packages/retouche/**'
              - './packages/adapter-github/**'
              - './.github/workflows/zugriff.yml'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js 24.4.0
        uses: actions/setup-node@v4
        with:
          node-version: 24.4.0
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - name: Extract Most Recent Commit Message
        run: |
          echo "COMMIT_MESSAGE=$(git log --pretty=oneline --abbrev-commit | head -n 1 | cut -c 1-128)" >> $GITHUB_ENV

      - uses: zugriffcloud/action-deploy@latest
        if: steps.filter.outputs.docs == 'true'
        with:
          cwd: ./apps/docs/.vitepress/dist
          name: ${{ env.COMMIT_MESSAGE }}
          deploymentToken: ${{ secrets.ZUGRIFF_TOKEN_DOCS }}
          preferPuppets: true
          preferFileRouter: true
          disableFunctionDiscovery: true
          interceptors: |
            404:/404.html
          assets: |
            .
            ../../zugriff-dark.svg
            ../../zugriff-light.svg
            ../../demo.png
            ../../favicon.png
          promotions: |
            production

      - uses: zugriffcloud/action-deploy@latest
        if: steps.filter.outputs.vanilla_ts == 'true'
        with:
          cwd: ./examples/vanilla-ts/dist
          name: (vanilla-ts) ${{ env.COMMIT_MESSAGE }}
          deploymentToken: ${{ secrets.ZUGRIFF_TOKEN_EXAMPLES }}
          disableFunctionDiscovery: true
          preferPuppets: true
          assets: |
            .
          promotions: |
            vanilla-ts
